name: Parameterized Pipeline

on:
  workflow_dispatch:
    inputs:
      fname:
        description: "First Name"
        required: true
        type: string
      lname:
        description: "Last Name"
        required: true
        type: string
      email:
        description: "Email"
        required: true
        type: string
      phone:
        description: "Mobile number"
        required: true
        type: int
      education:
        description: "Highest Education"
        required: true
        type: string
      grade:
        description: "Grade"
        required: false
        type: float
      experience: 
        description: "Experience"
        required: true
        type: float
      organization:
        description: "Current Organziation"
        required: true
        type: string
      last_organization:
        description: "Last Organization"
        required: true
        type: string
      tech_stack:
        description: "What is your primary skill"
        required: true
        type: string
      address:
        description: "Provide your address"
        required: true
        type: string
      vehicle:
        description: "Which vehicle you own?"
        required: true
        type: choice
        options:
          - 2 wheeler
          - 4 wheeler
      married:
        description: "Are you married"
        required: true
        type: boolean
      

jobs:
  print_details:
    runs-on: ubuntu-latest
    steps:
      - name: Printing input parameters
        run: |
          echo "First name: ${{ github.event.inputs.fname }} "
          echo "Last name: ${{ github.event.inputs.lname }} "
          echo "Current Organization: ${{ github.event.inputs.organization }}"
          echo "Vehicle type: ${{ github.event.inputs.vehicle }}"
          echo "Married: ${{ github.event.inputs.married }}"
          
          
      
    
